version: '3.9'

services:
  db:
    container_name: SeeDB_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: SeeDB
    ports:
      - "5432:5432"